// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Keep a single source of truth: generate the sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // Generate from the whole /docs tree
    },
  ],
};

export default sidebars;
